 version: 2

 build:
   os: ubuntu-24.04
   tools:
     nodejs: "22"
   jobs:
     install:
       # Install dependencies
       - cd docs/ && npm install
     build:
       # Build the site
       - cd docs/ && npm run build
       # Copy generated files into Read the Docs directory
       - mkdir --parents $READTHEDOCS_OUTPUT/html/
       - cp --verbose --recursive docs/out/* $READTHEDOCS_OUTPUT/html/
